/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-primary': '#490080',
        'on-tertiary-fixed': '#241a00',
        'on-background': '#e4e1e6',
        'primary-fixed': '#f0dbff',
        'inverse-on-surface': '#303033',
        'on-tertiary': '#3c2f00',
        'on-secondary-container': '#00311f',
        'on-primary-container': '#400071',
        'tertiary': '#e9c349',
        'surface-container-highest': '#353438',
        'surface-dim': '#131316',
        'tertiary-container': '#cba72f',
        'surface-variant': '#353438',
        'on-primary-fixed': '#2c0051',
        'surface-container-high': '#2a2a2d',
        'outline-variant': '#4d4354',
        'on-tertiary-container': '#4e3d00',
        'primary-container': '#b76dff',
        'on-secondary-fixed-variant': '#005236',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e4e1e6',
        'secondary-container': '#00a572',
        'surface-tint': '#ddb7ff',
        'surface': '#131316',
        'on-surface': '#e4e1e6',
        'surface-container': '#1f1f22',
        "tertiary-fixed": "#ffe088",
        "surface-dim": "#131316",
        "primary-fixed-dim": "#ddb7ff",
        "on-tertiary-fixed": "#241a00",
        "on-error-container": "#ffdad6",
        "surface-container": "#1f1f22",
        "secondary-container": "#00a572",
        "surface-container-highest": "#353438",
        "tertiary": "#e9c349",
        "inverse-on-surface": "#303033",
        "surface-container-lowest": "#0e0e11",
        "on-tertiary-fixed-variant": "#574500",
        "surface-tint": "#ddb7ff",
        "on-secondary-container": "#00311f",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#2c0051",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-low": "#1b1b1e",
        "tertiary-fixed-dim": "#e9c349",
        "on-tertiary": "#3c2f00",
        "primary-fixed": "#f0dbff",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#6900b3",
        "primary-container": "#b76dff",
        "on-surface-variant": "#cfc2d6",
        "error-container": "#93000a",
        "secondary-fixed": "#6ffbbe",
        "on-secondary": "#003824",
        "error": "#ffb4ab",
        "on-background": "#e4e1e6",
        "on-primary": "#490080",
        "background": "#131316",
        "on-tertiary-container": "#4e3d00",
        "secondary": "#4edea3",
        "on-secondary-fixed": "#002113",
        "tertiary-container": "#cba72f",
        "on-primary-container": "#400071",
        "surface-variant": "#353438",
        "outline": "#988d9f",
        "surface-container-high": "#2a2a2d",
        "inverse-primary": "#842bd2",
        "outline-variant": "#4d4354",
        "on-surface": "#e4e1e6",
        "surface": "#131316",
        "inverse-surface": "#e4e1e6",
        "primary": "#ddb7ff",
        "surface-bright": "#39393c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "title-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "title-md": ["20px", { "lineHeight": "28px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
